# Usa una imagen de node para construir la aplicación
FROM node:latest AS builder

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package.json .
# COPY yarn.lock .

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Construye la aplicación
RUN npm run build

# Ahora, configuramos el servidor web para servir la aplicación construida
FROM nginx:alpine

# Copia los archivos construidos de la etapa anterior al directorio de trabajo del servidor nginx
COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80
EXPOSE 80
