# Usa la imagen base de Node.js
FROM node:alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el package.json y el package-lock.json (si existen)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto en el que se ejecutará tu aplicación
EXPOSE 3000

# Comando para ejecutar tu aplicación
CMD ["npm", "start"]